### ISSUE TITLE
maxLength 设置后 第一行会新增一行

### ISSUE THREAD

**Issue by sxx1990** [wangfupeng1988/vue3-wangeditor-demo#1]
![2711657708812_ pic](https://user-images.githubusercontent.com/29890016/178715112-b24ff506-1bd7-44c8-802a-04978e3e4c72.jpg)

**Comment by wangfupeng1988** [comment]
已知问题，在这里跟踪：https://github.com/wangeditor-team/wangEditor/issues/4078
